[package]
name = "dishaster-godot-game"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
test = false

[dependencies]
dishrupt-core.workspace = true
dishrupt-asset.workspace = true
dishrupt-runner.workspace = true
dishrupt-l10n.workspace = true
dishrupt-godot-display.workspace = true
dishrupt-godot-input.workspace = true
dishrupt-godot-utils.workspace = true
dishaster-models.workspace = true
dishaster-views.workspace = true
dishaster-interface.workspace = true
dishaster-persistence.workspace = true
dishaster-ui-protocol.workspace = true

anyhow.workspace = true
rustc-hash.workspace = true
godot.workspace = true

[lints]
# workspace = true
