[package]
name = "dishaster-godot-game"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
dishrupt-core.workspace = true
dishrupt-persistence.workspace = true
dishrupt-godot.workspace = true
dishrupt-godot-ui.workspace = true
dishrupt-godot-scene.workspace = true
dishrupt-l10n.workspace = true
dishaster-models.workspace = true
dishaster-views.workspace = true
dishaster-interface.workspace = true
dishaster-persistence.workspace = true
dishaster-runner.workspace = true
dishaster-godot-ui.workspace = true

anyhow.workspace = true
rustc-hash.workspace = true
godot.workspace = true

[lints]
# workspace = true
