[package]
name = "dishaster-trial"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
dishrupt-core.workspace = true
dishrupt-rng.workspace = true
dishaster-models.workspace = true
dishaster-views.workspace = true

log.workspace = true
rustc-hash.workspace = true

[dev-dependencies]
insta = { workspace = true, features = ["yaml"] }
serde = { workspace = true }
dishaster-data.workspace = true
rand = { workspace = true }
rand_xoshiro = { workspace = true }

[lints]
workspace = true
