[workspace]
resolver = "3"
members = ["crates/*", "tests"]
default-members = ["crates/dishaster-godot-ext"]

[workspace.package]
version = "0.1.0"
authors = ["QuadnucYard"]
rust-version = "1.93"
edition = "2024"

[workspace.dependencies]
godot-binary-resource = { path = "crates/godot-binary-resource" }
fluent-loader = { path = "crates/fluent-loader" }
fluent-godot-loader = { path = "crates/fluent-godot-loader" }

dishrupt-core = { path = "crates/dishrupt-core" }
dishrupt-ecs = { path = "crates/dishrupt-ecs" }
dishrupt-rng = { path = "crates/dishrupt-rng" }
dishrupt-asset = { path = "crates/dishrupt-asset" }
dishrupt-persistence = { path = "crates/dishrupt-persistence" }
dishrupt-simulation = { path = "crates/dishrupt-simulation" }
dishrupt-runner = { path = "crates/dishrupt-runner" }
dishrupt-l10n = { path = "crates/dishrupt-l10n" }
dishrupt-l10n-godot = { path = "crates/dishrupt-l10n-godot" }
dishrupt-godot-audio = { path = "crates/dishrupt-godot-audio" }
dishrupt-godot-display = { path = "crates/dishrupt-godot-display" }
dishrupt-godot-input = { path = "crates/dishrupt-godot-input" }
dishrupt-godot-utils = { path = "crates/dishrupt-godot-utils" }
dishrupt-godot-ui = { path = "crates/dishrupt-godot-ui" }
dishrupt-godot-ui-macros = { path = "crates/dishrupt-godot-ui-macros" }
dishrupt-godot-widgets = { path = "crates/dishrupt-godot-widgets" }
dishrupt-godot-scene = { path = "crates/dishrupt-godot-scene" }

dishaster-navigation = { path = "crates/dishaster-navigation" }
dishaster-models = { path = "crates/dishaster-models" }
dishaster-save-models = { path = "crates/dishaster-save-models" }
dishaster-views = { path = "crates/dishaster-views" }
dishaster-interface = { path = "crates/dishaster-interface" }
dishaster-trial = { path = "crates/dishaster-trial" }
dishaster-core = { path = "crates/dishaster-core" }
dishaster-opening-models = { path = "crates/dishaster-opening-models" }
dishaster-opening = { path = "crates/dishaster-opening" }
dishaster-data = { path = "crates/dishaster-data" }
dishaster-persistence = { path = "crates/dishaster-persistence" }
dishaster-validation = { path = "crates/dishaster-validation" }
dishaster-ui-protocol = { path = "crates/dishaster-ui-protocol" }
dishaster-godot-ui = { path = "crates/dishaster-godot-ui" }
dishaster-godot-game = { path = "crates/dishaster-godot-game" }
dishaster-godot-opening = { path = "crates/dishaster-godot-opening" }
dishaster-godot = { path = "crates/dishaster-godot" }

bevy_color = { version = "0.17.0", default-features = false, features = ["std"] }
bevy_ecs = { version = "0.17.0", default-features = false, features = ["std", "backtrace"] }
bevy_math = { version = "0.17.0", default-features = false, features = ["std", "serialize"] }

godot = "0.4.2"

anyhow = "1.0"
arc-swap = "1.7"
as-any = "0.3"
backtrace = "0.3"
bincode = "2.0"
codespan-reporting = "0.13"
color-backtrace = "0.7"
derive_more = { version = "2", features = ["deref", "deref_mut"] }
dodgy = "0.3"
ecow = { version = "0.2", features = ["serde"] }
edt = "0.2"
enum-map = { version = "2.7", features = ["serde"] }
env_logger = { version = "0.11", default-features = false, features = ["auto-color", "humantime"] }
fibre = "0.5"
fluent-bundle = "0.16"
fluent-langneg = "0.13"
fluent-syntax = "0.12"
fluent-templates = { version = "0.13.2", default-features = false, features = ["walkdir"] }
grid = "1.0"
insta = { version = "1", features = ["yaml"] }
log = "0.4"
ordered-float = "5"
paste = "1.0"
pathfinding = "4.14.0"
rand = { version = "0.9", default-features = false, features = ["std"] }
rand_core = "0.9"
rand_distr = "0.5"
rand_xoshiro = "0.7"
ron = "0.12"
rustc-hash = "2"
serde = { version = "1.0", features = ["derive"] }
signals2 = "0.3"
slab = "0.4"
thiserror = "2.0"
tempfile = "3.10"
toml = "0.9"
unic-langid = "0.9"
variadics_please = "1.1"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[patch.crates-io]
godot = { git = "https://github.com/godot-rust/gdext", rev = "e01d2ea" } # For `max_align_t` issue

[profile.dev]
opt-level = 2

[profile.test]
opt-level = 1

[profile.profiling]
inherits = "release"
debug = true
