[workspace]
resolver = "3"
members = ["crates/*", "crates/dishrupt-godot-ui/macros"]
default-members = ["crates/dishaster-core", "crates/dishaster-godot-ext"]

[workspace.package]
version = "0.1.0"
authors = ["QuadnucYard"]
rust-version = "1.89"
edition = "2024"

[workspace.dependencies]
dishrupt-core = { path = "crates/dishrupt-core" }
dishrupt-godot = { path = "crates/dishrupt-godot" }
dishrupt-godot-ui = { path = "crates/dishrupt-godot-ui" }
dishrupt-godot-scene = { path = "crates/dishrupt-godot-scene" }

dishaster-navigation = { path = "crates/dishaster-navigation" }
dishaster-models = { path = "crates/dishaster-models" }
dishaster-core = { path = "crates/dishaster-core" }
dishaster-data = { path = "crates/dishaster-data" }
dishaster-godot-ui = { path = "crates/dishaster-godot-ui" }
dishaster-godot = { path = "crates/dishaster-godot" }

bevy_color = { version = "0.16", default-features = false, features = ["std"] }
bevy_ecs = { version = "0.16", default-features = false, features = [
  "std",
  "backtrace",
] }
bevy_math = { version = "0.16", default-features = false, features = ["std", "serialize"] }

godot = "0.3.5"

anyhow = "1.0"
as-any = "0.3"
derive_more = "1"
ecow = { version = "0.2", features = ["serde"] }
env_logger = "0.11"
fibre = "0.5"
log = "0.4"
pathfinding = "4.14.0"
rand = "0.9"
rand_core = "0.9"
rand_chacha = "0.9"
ron = "0.11"
rustc-hash = "2"
serde = { version = "1.0", features = ["derive"] }
signals2 = "0.3"
thiserror = "2.0"

[workspace.lints.rust]
missing_docs = "warn"

[workspace.lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[patch.crates-io]
godot = { git = "https://github.com/godot-rust/gdext", rev = "9da0f54" }

[profile.dev.package]
bevy_ecs.opt-level = 1
bevy_math.opt-level = 1
godot.opt-level = 1
