[package]
name = "dishaster-godot-ui"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
test = false

[dependencies]
dishrupt-core.workspace = true
dishrupt-asset.workspace = true
dishrupt-godot-ui.workspace = true
dishrupt-godot-ui-macros.workspace = true
dishrupt-godot-widgets.workspace = true
dishrupt-l10n-godot.workspace = true
dishaster-views.workspace = true
dishaster-ui-protocol.workspace = true

godot.workspace = true
signals2.workspace = true

[lints]
# workspace = true
