[package]
name = "dishaster-godot-ui"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
dishrupt-godot.workspace = true
dishrupt-godot-ui.workspace = true

godot.workspace = true
signals2.workspace = true

[lints]
# workspace = true
