[package]
name = "dishaster-tests"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[[test]]
name = "integration_test"
path = "src/integration_test.rs"
harness = false

[[test]]
name = "asset_validation"
path = "src/asset_validation.rs"

[[test]]
name = "management_l10n_snapshot"
path = "src/management_l10n_snapshot.rs"

[dependencies]
dishrupt-core.workspace = true
dishrupt-asset.workspace = true
dishrupt-rng.workspace = true
dishrupt-l10n.workspace = true
dishaster-core.workspace = true
dishaster-data.workspace = true
dishaster-persistence.workspace = true
dishaster-validation.workspace = true

anyhow.workspace = true
env_logger.workspace = true
insta.workspace = true
serde.workspace = true

[lints]
workspace = true
