[package]
name = "dishrupt-persistence"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
godot = { workspace = true, optional = true }

[features]
default = []
fs = []
godot = ["dep:godot"]

[lints]
workspace = true
