[package]
name = "dishaster-opening"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
dishrupt-core.workspace = true
dishrupt-ecs.workspace = true
dishrupt-rng.workspace = true
dishrupt-simulation.workspace = true

bevy_ecs.workspace = true
serde.workspace = true

[lints]
workspace = true
