
[kinds.scene]
prefix = "res://assets/scenes"
default_ext = "tscn"

[kinds.gui]
prefix = "res://assets/gui"
default_ext = "tscn"

[kinds.prefab]
prefix = "res://assets/prefabs"
default_ext = "tscn"

[kinds.texture]
prefix = "res://assets/sprites"

[kinds.music]
prefix = "res://assets/music"

[kinds.sound]
prefix = "res://assets/sounds"

[kinds.prefab.aliases]
dish_price_label = "price_label"

[kinds.music.aliases]
main_theme = "main_theme.ogg"
canteen_preparation_theme = "A Fresh Start.ogg"
canteen_running_theme = "Bustling Canteen Chaos.ogg"
canteen_settlement_theme = "Counting the Day's Success.ogg"
trial_theme = "Tension Rises.ogg"
