[package]
name = "dishaster-persistence"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
dishrupt-core.workspace = true
dishrupt-persistence.workspace = true
dishaster-save-models.workspace = true
dishaster-models.workspace = true # only for registry

anyhow.workspace = true
log.workspace = true
ron.workspace = true

[dev-dependencies]
dishrupt-core.workspace = true
dishrupt-persistence = { workspace = true, features = ["fs"] }
dishaster-models.workspace = true

tempfile.workspace = true

[lints]
workspace = true
