[package]
name = "dishaster-persistence"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
dishrupt-persistence.workspace = true
dishaster-models.workspace = true

anyhow.workspace = true
ron.workspace = true
rustc-hash.workspace = true
serde.workspace = true

[dev-dependencies]
dishrupt-core.workspace = true
dishrupt-persistence = { workspace = true, features = ["fs"] }
tempfile.workspace = true

[lints]
workspace = true
