[package]
name = "dishaster-godot-opening"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
test = false

[dependencies]
dishrupt-core.workspace = true
dishrupt-runner.workspace = true
dishrupt-godot.workspace = true
dishaster-opening.workspace = true

godot.workspace = true
rustc-hash.workspace = true

[lints]
workspace = true
