[package]
name = "fluent-godot-loader"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
test = false

[dependencies]
fluent-loader.workspace = true

fluent-bundle.workspace = true
fluent-langneg.workspace = true
godot.workspace = true
unic-langid.workspace = true

[lints]
workspace = true
