[package]
name = "dishaster-models"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
dishrupt-core.workspace = true
dishaster-save-models.workspace = true

enum-map.workspace = true
paste.workspace = true
serde.workspace = true

[lints]
workspace = true
