[package]
name = "dishaster-data"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
dishrupt-core.workspace = true
dishaster-models.workspace = true

anyhow.workspace = true
codespan-reporting = { workspace = true, optional = true }
log.workspace = true
serde.workspace = true
ron.workspace = true
thiserror.workspace = true
toml.workspace = true

[dev-dependencies]
dishaster-validation.workspace = true

[features]
default = ["codespan"]
codespan = ["codespan-reporting"]

[lints]
workspace = true
