[package]
name = "dishaster-data"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
dishrupt-core.workspace = true
dishaster-core.workspace = true

anyhow.workspace = true
serde.workspace = true
ron.workspace = true
thiserror.workspace = true

[lints]
workspace = true
