[package]
name = "dishaster-godot"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
dishrupt-godot.workspace = true
dishrupt-godot-ui.workspace = true
dishrupt-godot-scene.workspace = true
dishrupt-l10n-godot.workspace = true
dishaster-core.workspace = true
dishaster-interface.workspace = true
dishaster-data.workspace = true
dishaster-persistence.workspace = true
dishaster-ui-protocol.workspace = true
dishaster-godot-game.workspace = true
dishaster-godot-ui.workspace = true

env_logger.workspace = true
godot.workspace = true
log.workspace = true

[lints]
# workspace = true
