[package]
name = "dishaster-godot"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
test = false

[dependencies]
dishrupt-core.workspace = true
dishrupt-asset.workspace = true
dishrupt-godot.workspace = true
dishrupt-godot-ui.workspace = true
dishrupt-godot-scene.workspace = true
dishrupt-l10n-godot.workspace = true
dishaster-core.workspace = true
dishaster-data.workspace = true
dishaster-persistence.workspace = true
dishaster-ui-protocol.workspace = true
dishaster-godot-game.workspace = true
dishaster-godot-opening.workspace = true
dishaster-godot-ui.workspace = true

anyhow.workspace = true
backtrace.workspace = true
color-backtrace.workspace = true
env_logger.workspace = true
godot.workspace = true
log.workspace = true

[features]
default = ["debug"]
debug = []
trace = ["dishaster-core/trace"]

[lints]
# workspace = true
