[package]
name = "dishrupt-l10n"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
arc-swap.workspace = true
fluent-loader.workspace = true
fluent-bundle.workspace = true
fluent-templates.workspace = true
unic-langid.workspace = true

[lints]
workspace = true
