[package]
name = "dishaster-godot-ext"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
name = "dishaster"
crate-type = ["cdylib"] # Compile this crate to a dynamic C library.
test = false

[dependencies]
dishaster-godot.workspace = true

godot.workspace = true

[features]
default = []
production = ["dishaster-godot/production"]
web = [
  "production",
  "godot/api-custom",
  "godot/experimental-wasm",
  "godot/lazy-function-tables",
  "godot/experimental-wasm-nothreads",
]
trace = ["dishaster-godot/trace"]

[lints]
# workspace = true
