[package]
name = "dishrupt-asset"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
godot = { workspace = true, optional = true }
godot-binary-resource = { workspace = true, optional = true }
rustc-hash.workspace = true
serde.workspace = true
thiserror.workspace = true

[features]
default = []
godot = ["dep:godot", "godot-binary-resource"]

[lints]
workspace = true
