[package]
name = "dishaster-core"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
dishrupt-core.workspace = true
dishaster-models.workspace = true
dishaster-channel.workspace = true
dishaster-navigation.workspace = true

bevy_ecs.workspace = true
derive_more.workspace = true
log.workspace = true
ordered-float.workspace = true
rand.workspace = true
rand_xoshiro.workspace = true
rustc-hash.workspace = true
serde.workspace = true

[lints]
workspace = true
