[package]
name = "dishaster-core"
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
dishrupt-core.workspace = true
dishrupt-ecs.workspace = true
dishrupt-rng.workspace = true
dishrupt-simulation.workspace = true
dishaster-models.workspace = true
dishaster-save-models.workspace = true
dishaster-views.workspace = true
dishaster-interface.workspace = true
dishaster-navigation.workspace = true

bevy_ecs.workspace = true
log.workspace = true
ordered-float.workspace = true
rustc-hash.workspace = true

[features]
default = []
trace = ["bevy_ecs/trace"]

[lints]
workspace = true
