[package]
name = "dishrupt-godot-scene"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
test = false

[dependencies]
dishrupt-godot.workspace = true
dishrupt-godot-ui.workspace = true

godot.workspace = true
log.workspace = true

[lints]
# workspace = true
