[package]
name = "dishrupt-godot-scene"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
description = "Stack-based scene management system for Godot with transitions and lifecycle hooks"
readme = "README.md"

[lib]
test = false

[dependencies]
dishrupt-godot-audio.workspace = true
dishrupt-godot-input.workspace = true
dishrupt-godot-ui.workspace = true

godot.workspace = true
log.workspace = true

[lints]
workspace = true
