[package]
name = "dishrupt-godot-widgets"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
test = false

[dependencies]
dishrupt-godot-ui-macros.workspace = true

godot.workspace = true
signals2.workspace = true

[lints]
# workspace = true
