name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  pre_job:
    permissions:
      actions: write
      contents: read
    name: Duplicate Actions Detection
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: "true"
          paths: '["crates/**", "tests/**", "Cargo.toml", "Cargo.lock", ".github/workflows/ci.yml"]'
          paths_ignore: '["**/README.md"]'
          do_not_skip: '["workflow_dispatch"]'

  check:
    needs: [pre_job]
    if: needs.pre_job.outputs.should_skip != 'true'
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-11-15
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Run clippy (all features)
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Machete
        uses: bnjbvr/cargo-machete@main

  test:
    needs: [pre_job]
    if: needs.pre_job.outputs.should_skip != 'true'
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-11-15
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --tests --workspace
